### ISSUE TITLE
Request the resource of an image in Blog

### ISSUE THREAD

**Issue by longsizhuo** [zixiangcode/zixiangcode#1]
Hi Zixiang, I hope this message finds you well. I saw an image containing in your blogs. I'm trying to find the source of it. Do you have any idea? Maybe it is a skin of a [vtuber](https://www.youtube.com/@yukitoakiyama)
![image](https://github.com/user-attachments/assets/5442924b-8413-4afc-a8f6-b4bcc55bd3fe)

**Comment by zixiangcode** [comment]
Hello, Thank you for visiting.

This is a QQ expression package, you can find it at [this link](https://zb.vip.qq.com/hybrid/emoticonmall/detail?id=235438&traceDetail=base64-eyJhcHBpZCI6Im91dHNpZGUiLCJwYWdlX2lkIjoiNDciLCJpdGVtX2lkIjoiIiwiaXRlbV90eXBl
IjoiIn0=).

Regarding the author's information, I'm not sure if it's this [Bilibili UP](https://b23.tv/nlHqQAC). Perhaps you can try to get in touch with him and ask. 
Best wishes.

**Comment by longsizhuo** [comment]
Hi Zixiang,

Thanks for your kind reply, I think you are right. The only source we found
is that this is a QQ expression.

Thank you very much for your help! Have a nice day.

Best regards,
Siz

ZiXiang ***@***.***> 于2024年12月16日周一 10:59写道：
